//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 安徽省水土流失项目数据显示平台.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MyTYPE                      130
#define IDI_ICONWIN                     310
#define C                               310
#define IDD_DISPLAYVIEW                 311
#define IDI_ICONPIC                     312
#define IDI_ICONTAB                     313
#define IDI_ICONUSER                    314
#define IDI_ICONSTART                   315
#define IDI_ICONMENU                    316
#define IDI_ICONHELP                    317
#define DIALOG_LOGIN                    320
#define IDI_ICONLIST                    322
#define DIALOG_USER                     323
#define IDD_DIALOG1                     329
#define IDD_TUFENBIAO32                 329
#define DIALOG_PICTURE11                333
#define DIALOG_PICTURE21                335
#define DIALOG_PICTURE31                337
#define DIALOG_PICTURE41                341
#define IDD_TUDILIYONG                  343
#define IDD_TUJIEYITU11                 345
#define IDD_TUJIEYITU1                  345
#define IDD_TUZONGBIAO10                347
#define IDD_TUFENBIAO11                 349
#define IDD_TUFENBIAO12                 351
#define IDD_TUFENBIAO13                 353
#define IDD_TUDILIYONG1                 355
#define IDD_TUJIEYITU2                  357
#define IDD_TUZONGBIAO20                358
#define IDD_TUFENBIAO21                 361
#define IDD_TUFENBIAO22                 362
#define IDD_TUFENBIAO23                 363
#define IDD_TUDILIYONG2                 367
#define IDD_TUJIEYITU3                  369
#define IDD_TUZONGBIAO30                371
#define IDD_TUFENBIAO31                 372
#define IDD_TUDILIYONG3                 379
#define IDD_TUJIEYITU4                  381
#define IDD_TUZONGBIAO40                382
#define IDD_TUFENBIAO41                 383
#define IDD_TUFENBIAO42                 387
#define IDD_TUFENBIAO43                 388
#define IDD_ZHIBEIFUGAI1                391
#define IDD_ZHIBEIFUGAI2                393
#define IDD_ZHIBEIFUGAI3                394
#define IDD_ZHIBEIFUGAI4                395
#define IDD_SHUITULIUSHI1               399
#define IDD_SHUITULIUSHI2               400
#define IDD_SHUITULIUSHI3               401
#define IDD_SHUITULIUSHI4               402
#define IDD_ZHIJIEYITU1                 407
#define IDD_ZHIJIEYITU2                 408
#define IDD_ZHIJIEYITU3                 409
#define IDD_ZHIJIEYITU4                 410
#define IDD_SHUIJIEYITU1                417
#define IDD_SHUIJIEYITU2                418
#define IDD_SHUIJIEYITU3                419
#define IDD_SHUIJIEYITU4                420
#define IDD_ZHIZONGBIAO10               421
#define IDD_ZHIFENBIAO11                427
#define IDD_ZHIFENBIAO12                428
#define IDD_ZHIFENBIAO13                429
#define IDD_ZHIZONGBIAO20               433
#define IDD_ZHIFENBIAO21                434
#define IDD_ZHIFENBIAO22                435
#define IDD_ZHIFENBIAO23                436
#define IDD_ZHIZONGBIAO30               441
#define IDD_ZHIFENBIAO31                442
#define IDD_ZHIFENBIAO32                443
#define IDD_ZHIZONGBIAO40               444
#define IDD_ZHIFENBIAO41                445
#define IDD_ZHIFENBIAO42                451
#define IDD_ZHIFENBIAO43                452
#define IDD_SHUIZONGBIAO10              455
#define IDD_SHUIFENBIAO11               456
#define IDD_SHUIFENBIAO12               457
#define IDD_SHUIFENBIAO13               461
#define IDD_SHUIFENBIAO21               462
#define IDD_SHUIZONGBIAO20              463
#define IDD_SHUIFENBIAO22               464
#define IDD_SHUIFENBIAO23               465
#define IDD_SHUIZONGBIAO30              466
#define IDD_SHUIFENBIAO31               473
#define IDD_SHUIFENBIAO32               474
#define IDD_SHUIZONGBIAO40              475
#define IDD_SHUIFENBIAO41               476
#define IDD_SHUIFENBIAO42               477
#define IDD_SHUIFENBIAO43               478
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_BUTTON1                     1002
#define IDC_EDIT3                       1002
#define IDC_BUTTON2                     1003
#define IDC_EDIT4                       1003
#define IDC_BUTTON3                     1004
#define IDC_BUTTON4                     1005
#define IDC_TAB1                        1005
#define IDC_EDIT5                       1005
#define IDC_PIC11                       1013
#define IDC_PIC12                       1014
#define IDC_PIC22                       1015
#define IDC_PIC21                       1016
#define IDC_LIST1                       1017
#define IDC_PIC23                       1018
#define IDC_TUPIC                       1018
#define IDC_LIST2                       1018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        485
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
